Code Book
=========================

The "run_analysis.R" will read data which can be downloaded from https://d396qusza40orc.cloudfront.net/getdata%2Fprojectfiles%2FUCI%20HAR%20Dataset.zip

run_analysis.R" has the following functionality.

1. Merges the training and the test sets to create one data set
    * "/train/X_train.txt" with "/test/X_test.txt"
    * "/train/subject_train.txt" with "/test/subject_test.txt"
    * "/train/y_train.txt" with "/test/y_test.txt"
2. Extracts only the measurements on the mean and standard deviation for each measurement
    * It gets list of measurements from "/features.txt"
    * Extracts only the measurements on the mean and standard deviation for each measurement
    * Applied on result data set from "/train/X_train.txt" with "/test/X_test.txt" and used as labels.
3. Uses descriptive activity names to name the activities in the data set
    * It gets activities from "/activity_labels.txt"
    * Based on activity code in result data set from "/train/y_train.txt" with "/test/y_test.txt" it joins data to the data set from "/activity_labels.txt" and replaces activity codes with activity labels.
    * Name the variable "activity"
4. Appropriately labels the data set with descriptive variable names
    * Name the variable "subject" in result data set from "/train/subject_train.txt" with "/test/subject_test.txt"
    * Merge all three results data sets from the step one above.
    * Create "tidy.data.set" data frame
5. Creates a second, independent tidy data set with the average of each variable for each activity and each subject
    * Create "tidy.data.set.mean" which is derived from "tidy.data.set"; get mean of each column by activity and subject
    * Export "tidy.data.set.mean" data into "tidy.data.set.mean.txt" in current working directory

tidy.data.set.mean
-------------------------
### Variables

Column  | Original Name | Values
------------------ | ------------------ | ------------------
subject | | 1..30 
activity | | "laying", "sitting", "standing", "walking", "walking_downstairs", "walking_upstairs"  
tbodyacc.mean.x | tBodyAcc-mean()-X | -1..1
tbodyacc.mean.y | tBodyAcc-mean()-Y | -1..1
tbodyacc.mean.z | tBodyAcc-mean()-Z | -1..1
tbodyacc.std.x | tBodyAcc-std()-X | -1..1
tbodyacc.std.y | tBodyAcc-std()-Y | -1..1
tbodyacc.std.z | tBodyAcc-std()-Z | -1..1
tgravityacc.mean.x | tGravityAcc-mean()-X | -1..1
tgravityacc.mean.y | tGravityAcc-mean()-Y | -1..1
tgravityacc.mean.z | tGravityAcc-mean()-Z | -1..1
tyacc.std.x | tGravityAcc-std()-X | -1..1
tgravityacc.std.y | tGravityAcc-std()-Y | -1..1
tgravityacc.std.z | tGravityAcc-std()-Z | -1..1
tbodyaccjerk.mean.x | tBodyAccJerk-mean()-X | -1..1
tbodyaccjerk.mean.y | tBodyAccJerk-mean()-Y | -1..1
tbodyaccjerk.mean.z | tBodyAccJerk-mean()-Z | -1..1
tbodyaccjerk.std.x | tBodyAccJerk-std()-X | -1..1
tbodyaccjerk.std.y | tBodyAccJerk-std()-Y | -1..1
tbodyaccjerk.std.z | tBodyAccJerk-std()-Z | -1..1
tbodygyro.mean.x | tBodyGyro-mean()-X | -1..1
tbodygyro.mean.y | tBodyGyro-mean()-Y | -1..1
tbodygyro.mean.z | tBodyGyro-mean()-Z | -1..1
tbodygyro.std.x | tBodyGyro-std()-X | -1..1
tbodygyro.std.y | tBodyGyro-std()-Y | -1..1
tbodygyro.std.z | tBodyGyro-std()-Z | -1..1
tbodygyrojerk.mean.x | tBodyGyroJerk-mean()-X | -1..1
tbodygyrojerk.mean.y | tBodyGyroJerk-mean()-Y | -1..1
tbodygyrojerk.mean.z | tBodyGyroJerk-mean()-Z | -1..1
tbodygyrojerk.std.x | tBodyGyroJerk-std()-X | -1..1
tbodygyrojerk.std.y | tBodyGyroJerk-std()-Y | -1..1
tbodygyrojerk.std.z | tBodyGyroJerk-std()-Z | -1..1
tbodyaccmag.mean | tBodyAccMag-mean() | -1..1
tbodyaccmag.std | tBodyAccMag-std() | -1..1
tgravityaccmag.mean | tGravityAccMag-mean() | -1..1
tgravityaccmag.std | tGravityAccMag-std() | -1..1
tbodyaccjerkmag.mean | tBodyAccJerkMag-mean() | -1..1
tbodyaccjerkmag.std | tBodyAccJerkMag-std() | -1..1
tbodygyromag.mean | tBodyGyroMag-mean() | -1..1
tbodygyromag.std | tBodyGyroMag-std() | -1..1
tbodygyrojerkmag.mean | tBodyGyroJerkMag-mean() | -1..1
tbodygyrojerkmag.std | tBodyGyroJerkMag-std() | -1..1
fbodyacc.mean.x | fBodyAcc-mean()-X | -1..1
fbodyacc.mean.y | fBodyAcc-mean()-Y | -1..1
fbodyacc.mean.z | fBodyAcc-mean()-Z | -1..1
fbodyacc.std.x | fBodyAcc-std()-X | -1..1
fbodyacc.std.y | fBodyAcc-std()-Y | -1..1
fbodyacc.std.z | fBodyAcc-std()-Z | -1..1
fbodyaccjerk.mean.x | fBodyAccJerk-mean()-X | -1..1
fbodyaccjerk.mean.y | fBodyAccJerk-mean()-Y | -1..1
fbodyaccjerk.mean.z | fBodyAccJerk-mean()-Z | -1..1
fbodyaccjerk.std.x | fBodyAccJerk-std()-X | -1..1
fbodyaccjerk.std.y | fBodyAccJerk-std()-Y | -1..1
fbodyaccjerk.std.z | fBodyAccJerk-std()-Z | -1..1
fbodygyro.mean.x | fBodyGyro-mean()-X | -1..1
fbodygyro.mean.y | fBodyGyro-mean()-Y | -1..1
fbodygyro.mean.z | fBodyGyro-mean()-Z | -1..1
fbodygyro.std.x | fBodyGyro-std()-X | -1..1
fbodygyro.std.y | fBodyGyro-std()-Y | -1..1
fbodygyro.std.z | fBodyGyro-std()-Z | -1..1
fbodyaccmag.mean | fBodyAccMag-mean() | -1..1
fbodyaccmag.std | fBodyAccMag-std() | -1..1
fbodybodyaccjerkmag.mean | fBodyBodyAccJerkMag-mean() | -1..1
fbodybodyaccjerkmag.std | fBodyBodyAccJerkMag-std() | -1..1
fbodybodygyromag.mean | fBodyBodyGyroMag-mean() | -1..1
fbodybodygyromag.std | fBodyBodyGyroMag-std() | -1..1
fbodybodygyrojerkmag.mean | fBodyBodyGyroJerkMag-mean() | -1..1
fbodybodygyrojerkmag.std | fBodyBodyGyroJerkMag-std() | -1..1
### Structure
```
> str(tidy.data.set.mean)
'data.frame':    180 obs. of  68 variables:
 $ activity                 : chr  "laying" "sitting" "standing" "walking" ...
 $ subject                  : int  1 1 1 1 1 1 2 2 2 2 ...
 $ tbodyacc.mean.x          : num  0.222 0.261 0.279 0.277 0.289 ...
 $ tbodyacc.mean.y          : num  -0.04051 -0.00131 -0.01614 -0.01738 -0.00992 ...
 $ tbodyacc.mean.z          : num  -0.113 -0.105 -0.111 -0.111 -0.108 ...
 $ tbodyacc.std.x           : num  -0.928 -0.977 -0.996 -0.284 0.03 ...
 $ tbodyacc.std.y           : num  -0.8368 -0.9226 -0.9732 0.1145 -0.0319 ...
 $ tbodyacc.std.z           : num  -0.826 -0.94 -0.98 -0.26 -0.23 ...
 $ tgravityacc.mean.x       : num  -0.249 0.832 0.943 0.935 0.932 ...
 $ tgravityacc.mean.y       : num  0.706 0.204 -0.273 -0.282 -0.267 ...
 $ tgravityacc.mean.z       : num  0.4458 0.332 0.0135 -0.0681 -0.0621 ...
 $ tgravityacc.std.x        : num  -0.897 -0.968 -0.994 -0.977 -0.951 ...
 $ tgravityacc.std.y        : num  -0.908 -0.936 -0.981 -0.971 -0.937 ...
 $ tgravityacc.std.z        : num  -0.852 -0.949 -0.976 -0.948 -0.896 ...
 $ tbodyaccjerk.mean.x      : num  0.0811 0.0775 0.0754 0.074 0.0542 ...
 $ tbodyaccjerk.mean.y      : num  0.003838 -0.000619 0.007976 0.028272 0.02965 ...
 $ tbodyaccjerk.mean.z      : num  0.01083 -0.00337 -0.00369 -0.00417 -0.01097 ...
 $ tbodyaccjerk.std.x       : num  -0.9585 -0.9864 -0.9946 -0.1136 -0.0123 ...
 $ tbodyaccjerk.std.y       : num  -0.924 -0.981 -0.986 0.067 -0.102 ...
 $ tbodyaccjerk.std.z       : num  -0.955 -0.988 -0.992 -0.503 -0.346 ...
 $ tbodygyro.mean.x         : num  -0.0166 -0.0454 -0.024 -0.0418 -0.0351 ...
 $ tbodygyro.mean.y         : num  -0.0645 -0.0919 -0.0594 -0.0695 -0.0909 ...
 $ tbodygyro.mean.z         : num  0.1487 0.0629 0.0748 0.0849 0.0901 ...
 $ tbodygyro.std.x          : num  -0.874 -0.977 -0.987 -0.474 -0.458 ...
 $ tbodygyro.std.y          : num  -0.9511 -0.9665 -0.9877 -0.0546 -0.1263 ...
 $ tbodygyro.std.z          : num  -0.908 -0.941 -0.981 -0.344 -0.125 ...
 $ tbodygyrojerk.mean.x     : num  -0.1073 -0.0937 -0.0996 -0.09 -0.074 ...
 $ tbodygyrojerk.mean.y     : num  -0.0415 -0.0402 -0.0441 -0.0398 -0.044 ...
 $ tbodygyrojerk.mean.z     : num  -0.0741 -0.0467 -0.049 -0.0461 -0.027 ...
 $ tbodygyrojerk.std.x      : num  -0.919 -0.992 -0.993 -0.207 -0.487 ...
 $ tbodygyrojerk.std.y      : num  -0.968 -0.99 -0.995 -0.304 -0.239 ...
 $ tbodygyrojerk.std.z      : num  -0.958 -0.988 -0.992 -0.404 -0.269 ...
 $ tbodyaccmag.mean         : num  -0.8419 -0.9485 -0.9843 -0.137 0.0272 ...
 $ tbodyaccmag.std          : num  -0.7951 -0.9271 -0.9819 -0.2197 0.0199 ...
 $ tgravityaccmag.mean      : num  -0.8419 -0.9485 -0.9843 -0.137 0.0272 ...
 $ tgravityaccmag.std       : num  -0.7951 -0.9271 -0.9819 -0.2197 0.0199 ...
 $ tbodyaccjerkmag.mean     : num  -0.9544 -0.9874 -0.9924 -0.1414 -0.0894 ...
 $ tbodyaccjerkmag.std      : num  -0.9282 -0.9841 -0.9931 -0.0745 -0.0258 ...
 $ tbodygyromag.mean        : num  -0.8748 -0.9309 -0.9765 -0.161 -0.0757 ...
 $ tbodygyromag.std         : num  -0.819 -0.935 -0.979 -0.187 -0.226 ...
 $ tbodygyrojerkmag.mean    : num  -0.963 -0.992 -0.995 -0.299 -0.295 ...
 $ tbodygyrojerkmag.std     : num  -0.936 -0.988 -0.995 -0.325 -0.307 ...
 $ fbodyacc.mean.x          : num  -0.9391 -0.9796 -0.9952 -0.2028 0.0382 ...
 $ fbodyacc.mean.y          : num  -0.86707 -0.94408 -0.97707 0.08971 0.00155 ...
 $ fbodyacc.mean.z          : num  -0.883 -0.959 -0.985 -0.332 -0.226 ...
 $ fbodyacc.std.x           : num  -0.9244 -0.9764 -0.996 -0.3191 0.0243 ...
 $ fbodyacc.std.y           : num  -0.834 -0.917 -0.972 0.056 -0.113 ...
 $ fbodyacc.std.z           : num  -0.813 -0.934 -0.978 -0.28 -0.298 ...
 $ fbodyaccjerk.mean.x      : num  -0.9571 -0.9866 -0.9946 -0.1705 -0.0277 ...
 $ fbodyaccjerk.mean.y      : num  -0.9225 -0.9816 -0.9854 -0.0352 -0.1287 ...
 $ fbodyaccjerk.mean.z      : num  -0.948 -0.986 -0.991 -0.469 -0.288 ...
 $ fbodyaccjerk.std.x       : num  -0.9642 -0.9875 -0.9951 -0.1336 -0.0863 ...
 $ fbodyaccjerk.std.y       : num  -0.932 -0.983 -0.987 0.107 -0.135 ...
 $ fbodyaccjerk.std.z       : num  -0.961 -0.988 -0.992 -0.535 -0.402 ...
 $ fbodygyro.mean.x         : num  -0.85 -0.976 -0.986 -0.339 -0.352 ...
 $ fbodygyro.mean.y         : num  -0.9522 -0.9758 -0.989 -0.1031 -0.0557 ...
 $ fbodygyro.mean.z         : num  -0.9093 -0.9513 -0.9808 -0.2559 -0.0319 ...
 $ fbodygyro.std.x          : num  -0.882 -0.978 -0.987 -0.517 -0.495 ...
 $ fbodygyro.std.y          : num  -0.9512 -0.9623 -0.9871 -0.0335 -0.1814 ...
 $ fbodygyro.std.z          : num  -0.917 -0.944 -0.982 -0.437 -0.238 ...
 $ fbodyaccmag.mean         : num  -0.8618 -0.9478 -0.9854 -0.1286 0.0966 ...
 $ fbodyaccmag.std          : num  -0.798 -0.928 -0.982 -0.398 -0.187 ...
 $ fbodybodyaccjerkmag.mean : num  -0.9333 -0.9853 -0.9925 -0.0571 0.0262 ...
 $ fbodybodyaccjerkmag.std  : num  -0.922 -0.982 -0.993 -0.103 -0.104 ...
 $ fbodybodygyromag.mean    : num  -0.862 -0.958 -0.985 -0.199 -0.186 ...
 $ fbodybodygyromag.std     : num  -0.824 -0.932 -0.978 -0.321 -0.398 ...
 $ fbodybodygyrojerkmag.mean: num  -0.942 -0.99 -0.995 -0.319 -0.282 ...
 $ fbodybodygyrojerkmag.std : num  -0.933 -0.987 -0.995 -0.382 -0.392 ...
```

Below is auto-generated codebook for tidy.data.set data frame by using "codebook" method from "memisc" package.


```{r}
source("run_analysis.R")
library(memisc)
codebook(data.set(tidy.data.set))
```

